### ISSUE TITLE
Water Sensor

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [dynasticorpheus/gigasetelements-ha#14]
Logger: homeassistant.components.binary_sensor
Source: custom_components/gigasetelements/binary_sensor.py:71
Integration: Binärsensor (documentation, issues)
First occurred: 16:24:46 (3 occurrences)
Last logged: 16:24:47

Error adding entities for domain binary_sensor with platform gigasetelements
Error while setting up gigasetelements platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 314, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    device_class=entity.device_class,
  File "/config/custom_components/gigasetelements/binary_sensor.py", line 71, in device_class
    return DEVICE_CLASS_MAP[self._type_name]
KeyError: 'water'

**Comment by helmut-hoffer-von-ankershoffen** [comment]
Seems like adding a water->moisture mapping in DEVICE_CLASS_MAP fixes it. Can you add to mainline?

**Comment by dynasticorpheus** [comment]
@helmut-hoffer-von-ankershoffen  Thanks for reporting, should be fixed via aa0da49
